/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d93ecb14-c1e4-4f26-868e-41b7c109e0f6",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_FjnI7NFlo",
    "aws_user_pools_web_client_id": "4sbrsg09hiq370i2qdklflntl3",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "newamplifyworkshopitems-dev",
            "region": "us-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "newamplifyworkshopapi",
            "endpoint": "https://c86f0wzql2.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_mobile_analytics_app_id": "c311b10b1ed04423b4b479ddbcb80d85",
    "aws_mobile_analytics_app_region": "us-west-2",
    "aws_content_delivery_bucket": "newamplifyecommerce-20210720064438-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://dq8itx3s2kf4v.cloudfront.net"
};


export default awsmobile;
